-- Aereon Dashboard — Property tab: Aereon's home loans.
-- Replaces the "Interest Rate" Numbers sheet. Only raw inputs are stored; principal,
-- interest, full-rate interest and the flexi saving are worked out in lib/property-math.ts.
-- Additive: four new tables, nothing existing touched. Safe to run twice. No data here: the repo is
-- public, so loans, months, findings and bank rates are loaded by `npm run property:import`.

-- One row per loan.
create table if not exists property_loan (
  id            text primary key,                  -- short slug per loan
  name          text not null,
  location      text,
  bank          text not null,                     -- must match property_bank_rate.bank
  loan_type     text,                              -- 'Full flexi'
  rate_basis    text not null default 'BR' check (rate_basis in ('BR','SBR')),
  spread        numeric(5,2) not null,             -- fixed in the letter of offer ("BR Add")
  cycle_day     int not null default 1 check (cycle_day between 1 and 28),  -- day the instalment is taken
  loan_amount   numeric(12,2),
  tenure_months int,
  first_month   date not null,
  notes         text,
  sort          int not null default 0
);

-- One row per loan per month: what the statement says.
create table if not exists property_loan_month (
  property_id          text not null references property_loan(id),
  month                date not null,              -- first of the month
  opening_balance      numeric(12,2),              -- blank = last month's outstanding; set only when the bank added to it
  outstanding_balance  numeric(12,2),              -- the one figure typed in each month ("Latest")
  instalment           numeric(12,2),              -- amount taken that month ("Monthly Repayment")
  interest_charged     numeric(12,2),              -- optional, straight from the statement; blank = instalment − principal
  status   text not null default 'normal' check (status in ('normal','moratorium','interest_only','pending','missing')),
  quality  text not null default 'unchecked' check (quality in ('statement','derived','estimated','unchecked')),
  note       text,
  updated_at timestamptz not null default now(),
  primary key (property_id, month)
);

-- The banks' published reference rates, so the rate is never typed by hand.
create table if not exists property_bank_rate (
  bank           text not null,
  effective_date date not null,
  base_rate      numeric(5,2),                     -- BR
  sbr            numeric(5,2),                     -- Standardised Base Rate (from Aug 2022)
  source         text,
  primary key (bank, effective_date)
);

-- What the move from the spreadsheet found, and what was done about it.
create table if not exists property_data_issue (
  id              bigint generated by default as identity primary key,
  property_id     text not null references property_loan(id),
  month           date,
  month_to        date,
  field           text,
  current_value   text,
  suggested_value text,
  severity        text not null check (severity in ('high','medium','low')),
  explanation     text not null,
  status          text not null default 'open' check (status in ('open','fixed','ignored')),
  resolution      text
);

-- Server-side only, like every other table here: RLS on, no policies.
alter table property_loan        enable row level security;
alter table property_loan_month  enable row level security;
alter table property_bank_rate   enable row level security;
alter table property_data_issue  enable row level security;

