-- Aereon Dashboard — Property tab: sub-meter billing for a dual-key property (main unit + studio on split meters).
-- Additive: two new tables, nothing existing touched. Safe to run twice. No data here: the repo is
-- public, so the readings and TNB bills are loaded by `npm run property:import -- --submeter`
-- (from .property-data/submeter.json) or typed on the Sub-meter page.

-- One row per reading of one unit's meter. The usage between two readings is worked out on the page.
create table if not exists submeter_reading (
  id          bigint generated by default as identity primary key,
  property_id text not null references property_loan(id),
  unit        text not null,                      -- e.g. 'Main unit', 'Studio'
  read_on     date not null,
  reading     numeric(12,2) not null check (reading >= 0),
  rate        numeric(6,4) check (rate >= 0),     -- RM per kWh charged for the usage since the previous reading; blank = a starting point
  legacy      boolean not null default false,     -- recorded before the flat rate (kept as history)
  note        text,
  created_at  timestamptz not null default now(),
  unique (property_id, unit, read_on)
);
create index if not exists submeter_reading_property on submeter_reading (property_id, unit, read_on);

-- One row per TNB bill, issued on the 12th. kW and kVARh are noted for reference; only kWh is billed.
create table if not exists submeter_bill (
  id          bigint generated by default as identity primary key,
  property_id text not null references property_loan(id),
  bill_date   date not null,                      -- the 12th the bill was issued
  amount      numeric(10,2) not null check (amount >= 0),
  kwh         numeric(10,2),                      -- blank when only the amount is known
  kw          numeric(8,2),
  kvarh       numeric(10,2),
  note        text,
  created_at  timestamptz not null default now(),
  unique (property_id, bill_date)
);

-- Who each unit's usage is billed to (added 4 Oct 2026). Set on the reading that closes the usage, so a new tenant
-- in the same unit starts on their first reading. It matches the tenant name on the Tenancy page. Electricity is
-- collected from the tenant, never counted as a property cost.
alter table submeter_reading add column if not exists tenant_name text;

-- When the tenant paid the charge on this reading (added 4 Oct 2026). Blank = still to collect. Typed when the
-- money arrives, or later: it is the real payment date, not the day it was recorded.
alter table submeter_reading add column if not exists paid_on date;

-- What a reading marks (added 5 Oct 2026): 'reading' bills the usage since the previous one; 'move_out' is a
-- tenant's final reading (billed as usual); 'move_in' is a new tenant's starting number, never a charge. Usage that
-- ends at a move-in reading happened between tenants and is billed to nobody.
alter table submeter_reading add column if not exists kind text not null default 'reading' check (kind in ('reading', 'move_in', 'move_out'));

-- Server-side only, like every other table here: RLS on, no policies.
alter table submeter_reading enable row level security;
alter table submeter_bill    enable row level security;
