-- Aereon Dashboard — Property tab: tenancy and running costs for a rented-out property.
-- Additive: two new tables, nothing existing touched. Safe to run twice. No data here: the repo is
-- public, so the tenancy terms are loaded by `npm run property:import` (from .property-data/).

-- One row per tenancy term (a renewal is a new row), so rent changes keep their history.
create table if not exists property_tenancy (
  id            bigint generated by default as identity primary key,
  property_id   text not null references property_loan(id),
  start_date    date not null,
  end_date      date not null,                    -- last day of the term
  monthly_rent  numeric(10,2),                    -- blank = not entered yet
  advance_rent       numeric(10,2),               -- first month's rent, paid in advance
  security_deposit   numeric(10,2),               -- refundable, usually 2 months
  utility_deposit    numeric(10,2),               -- refundable, usually half a month
  access_card_deposit numeric(10,2),              -- refundable, per card x number of cards
  deposit_refunded    numeric(10,2),              -- what was actually paid back to the tenant at the end
  tenant_name   text,
  notes         text,
  created_at    timestamptz not null default now(),
  check (end_date > start_date)
);

-- What the property costs to keep: maintenance fee, repairs, agent fee, stamping fee, anything else. One row per bill.
create table if not exists property_cost (
  id            bigint generated by default as identity primary key,
  property_id   text not null references property_loan(id),
  cost_date     date not null,
  kind          text not null default 'repair' check (kind in ('maintenance_fee','repair','agent_fee','stamping_fee','other')),
  amount        numeric(10,2) not null check (amount >= 0),
  description   text,
  vendor        text,
  tenant_name   text,                             -- the tenant this bill belongs to (agent fee, ...); blank = the property's own
  recovered_from_deposit boolean not null default false, -- paid by the owner but deducted from the tenant's deposit: not a cost to the owner
  created_at    timestamptz not null default now()
);
create index if not exists property_cost_property_date on property_cost (property_id, cost_date desc);

-- Server-side only, like every other table here: RLS on, no policies.
alter table property_tenancy enable row level security;
alter table property_cost    enable row level security;

-- Upgrade for tables made by the first version of this file. Safe to run twice; no-ops on a fresh install.
alter table property_tenancy drop column if exists deposit;
alter table property_tenancy add column if not exists advance_rent        numeric(10,2);
alter table property_tenancy add column if not exists security_deposit    numeric(10,2);
alter table property_tenancy add column if not exists utility_deposit     numeric(10,2);
alter table property_tenancy add column if not exists access_card_deposit numeric(10,2);
alter table property_cost    add column if not exists tenant_name         text;
alter table property_tenancy add column if not exists deposit_refunded    numeric(10,2);
alter table property_cost    add column if not exists recovered_from_deposit boolean not null default false;
